/* ankieta-listy.js — tłumaczenia treści generowanych przez JS w ankiecie
   (listy krajów/pokrewieństwa/podstawy pobytu, domyślne opcje, etykiety i wiersze dynamiczne).
   Kolejność krajów MUSI odpowiadać tablicy COUNTRIES w formularzu. Województwa zostają po polsku
   (nazwy administracyjne zgodne z dokumentami) — tłumaczona jest tylko etykieta i opcja domyślna. */
window.FORM_L10N = (function(){
  var COUNTRIES_EN = ["Afghanistan","Albania","Algeria","Andorra","Angola","Antigua and Barbuda","Argentina","Armenia","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Chile","China","Croatia","Cyprus","Chad","Czechia","Denmark","Congo","Dominican Republic","Dominica","Djibouti","Egypt","Ecuador","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Philippines","Finland","France","Gabon","Gambia","Ghana","Greece","Grenada","Georgia","Guyana","Haiti","Netherlands","Honduras","India","Indonesia","Iraq","Iran","Ireland","Iceland","Israel","Jamaica","Japan","Yemen","Cambodia","Cameroon","Canada","Qatar","Kazakhstan","Kenya","Kyrgyzstan","Kiribati","Colombia","Comoros","Democratic Republic of the Congo","North Korea","South Korea","Costa Rica","Cuba","Kuwait","Laos","Lesotho","Lebanon","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Latvia","North Macedonia","Madagascar","Malawi","Maldives","Malaysia","Mali","Malta","Morocco","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Mozambique","Namibia","Nauru","Nepal","Germany","Nigeria","Nicaragua","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","Poland","Portugal","South Africa","Russia","Romania","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","El Salvador","Samoa","San Marino","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","Somalia","Sri Lanka","United States","Swaziland","Sudan","South Sudan","Suriname","Syria","Switzerland","Sweden","Tajikistan","Thailand","Tanzania","Timor-Leste","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Ukraine","Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","United Kingdom","Vietnam","Italy","Ivory Coast","Marshall Islands","Solomon Islands","Zambia","Zimbabwe"];
  var COUNTRIES_ES = ["Afganistán","Albania","Argelia","Andorra","Angola","Antigua y Barbuda","Argentina","Armenia","Australia","Austria","Azerbaiyán","Bahamas","Baréin","Bangladés","Barbados","Bielorrusia","Bélgica","Belice","Benín","Bután","Bolivia","Bosnia y Herzegovina","Botsuana","Brasil","Brunéi","Bulgaria","Burkina Faso","Burundi","Chile","China","Croacia","Chipre","Chad","Chequia","Dinamarca","Congo","República Dominicana","Dominica","Yibuti","Egipto","Ecuador","Eritrea","Estonia","Esuatini","Etiopía","Fiyi","Filipinas","Finlandia","Francia","Gabón","Gambia","Ghana","Grecia","Granada","Georgia","Guyana","Haití","Países Bajos","Honduras","India","Indonesia","Irak","Irán","Irlanda","Islandia","Israel","Jamaica","Japón","Yemen","Camboya","Camerún","Canadá","Catar","Kazajistán","Kenia","Kirguistán","Kiribati","Colombia","Comoras","República Democrática del Congo","Corea del Norte","Corea del Sur","Costa Rica","Cuba","Kuwait","Laos","Lesoto","Líbano","Liberia","Libia","Liechtenstein","Lituania","Luxemburgo","Letonia","Macedonia del Norte","Madagascar","Malaui","Maldivas","Malasia","Malí","Malta","Marruecos","Mauritania","Mauricio","México","Micronesia","Moldavia","Mónaco","Mongolia","Mozambique","Namibia","Nauru","Nepal","Alemania","Nigeria","Nicaragua","Noruega","Omán","Pakistán","Palaos","Panamá","Papúa Nueva Guinea","Paraguay","Perú","Polonia","Portugal","Sudáfrica","Rusia","Rumanía","Ruanda","San Cristóbal y Nieves","Santa Lucía","San Vicente y las Granadinas","El Salvador","Samoa","San Marino","Senegal","Serbia","Seychelles","Sierra Leona","Singapur","Eslovaquia","Eslovenia","Somalia","Sri Lanka","Estados Unidos","Suazilandia","Sudán","Sudán del Sur","Surinam","Siria","Suiza","Suecia","Tayikistán","Tailandia","Tanzania","Timor Oriental","Togo","Tonga","Trinidad y Tobago","Túnez","Turquía","Turkmenistán","Tuvalu","Ucrania","Uruguay","Uzbekistán","Vanuatu","Ciudad del Vaticano","Venezuela","Reino Unido","Vietnam","Italia","Costa de Marfil","Islas Marshall","Islas Salomón","Zambia","Zimbabue"];
  var COUNTRIES_UK = ["Афганістан","Албанія","Алжир","Андорра","Ангола","Антигуа і Барбуда","Аргентина","Вірменія","Австралія","Австрія","Азербайджан","Багамські Острови","Бахрейн","Бангладеш","Барбадос","Білорусь","Бельгія","Беліз","Бенін","Бутан","Болівія","Боснія і Герцеговина","Ботсвана","Бразилія","Бруней","Болгарія","Буркіна-Фасо","Бурунді","Чилі","Китай","Хорватія","Кіпр","Чад","Чехія","Данія","Конго","Домініканська Республіка","Домініка","Джибуті","Єгипет","Еквадор","Еритрея","Естонія","Есватіні","Ефіопія","Фіджі","Філіппіни","Фінляндія","Франція","Габон","Гамбія","Гана","Греція","Гренада","Грузія","Гаяна","Гаїті","Нідерланди","Гондурас","Індія","Індонезія","Ірак","Іран","Ірландія","Ісландія","Ізраїль","Ямайка","Японія","Ємен","Камбоджа","Камерун","Канада","Катар","Казахстан","Кенія","Киргизстан","Кірибаті","Колумбія","Коморські Острови","Демократична Республіка Конго","Північна Корея","Південна Корея","Коста-Рика","Куба","Кувейт","Лаос","Лесото","Ліван","Ліберія","Лівія","Ліхтенштейн","Литва","Люксембург","Латвія","Північна Македонія","Мадагаскар","Малаві","Мальдіви","Малайзія","Малі","Мальта","Марокко","Мавританія","Маврикій","Мексика","Мікронезія","Молдова","Монако","Монголія","Мозамбік","Намібія","Науру","Непал","Німеччина","Нігерія","Нікарагуа","Норвегія","Оман","Пакистан","Палау","Панама","Папуа-Нова Гвінея","Парагвай","Перу","Польща","Португалія","Південно-Африканська Республіка","Росія","Румунія","Руанда","Сент-Кітс і Невіс","Сент-Люсія","Сент-Вінсент і Гренадини","Сальвадор","Самоа","Сан-Марино","Сенегал","Сербія","Сейшельські Острови","Сьєрра-Леоне","Сінгапур","Словаччина","Словенія","Сомалі","Шрі-Ланка","Сполучені Штати","Свазіленд","Судан","Південний Судан","Суринам","Сирія","Швейцарія","Швеція","Таджикистан","Таїланд","Танзанія","Східний Тимор","Того","Тонга","Тринідад і Тобаго","Туніс","Туреччина","Туркменістан","Тувалу","Україна","Уругвай","Узбекистан","Вануату","Ватикан","Венесуела","Велика Британія","В'єтнам","Італія","Кот-д'Івуар","Маршаллові Острови","Соломонові Острови","Замбія","Зімбабве"];
  var COUNTRIES_RU = ["Афганистан","Албания","Алжир","Андорра","Ангола","Антигуа и Барбуда","Аргентина","Армения","Австралия","Австрия","Азербайджан","Багамы","Бахрейн","Бангладеш","Барбадос","Беларусь","Бельгия","Белиз","Бенин","Бутан","Боливия","Босния и Герцеговина","Ботсвана","Бразилия","Бруней","Болгария","Буркина-Фасо","Бурунди","Чили","Китай","Хорватия","Кипр","Чад","Чехия","Дания","Конго","Доминиканская Республика","Доминика","Джибути","Египет","Эквадор","Эритрея","Эстония","Эсватини","Эфиопия","Фиджи","Филиппины","Финляндия","Франция","Габон","Гамбия","Гана","Греция","Гренада","Грузия","Гайана","Гаити","Нидерланды","Гондурас","Индия","Индонезия","Ирак","Иран","Ирландия","Исландия","Израиль","Ямайка","Япония","Йемен","Камбоджа","Камерун","Канада","Катар","Казахстан","Кения","Киргизия","Кирибати","Колумбия","Коморы","Демократическая Республика Конго","Северная Корея","Южная Корея","Коста-Рика","Куба","Кувейт","Лаос","Лесото","Ливан","Либерия","Ливия","Лихтенштейн","Литва","Люксембург","Латвия","Северная Македония","Мадагаскар","Малави","Мальдивы","Малайзия","Мали","Мальта","Марокко","Мавритания","Маврикий","Мексика","Микронезия","Молдова","Монако","Монголия","Мозамбик","Намибия","Науру","Непал","Германия","Нигерия","Никарагуа","Норвегия","Оман","Пакистан","Палау","Панама","Папуа — Новая Гвинея","Парагвай","Перу","Польша","Португалия","Южно-Африканская Республика","Россия","Румыния","Руанда","Сент-Китс и Невис","Сент-Люсия","Сент-Винсент и Гренадины","Сальвадор","Самоа","Сан-Марино","Сенегал","Сербия","Сейшелы","Сьерра-Леоне","Сингапур","Словакия","Словения","Сомали","Шри-Ланка","Соединённые Штаты","Свазиленд","Судан","Южный Судан","Суринам","Сирия","Швейцария","Швеция","Таджикистан","Таиланд","Танзания","Восточный Тимор","Того","Тонга","Тринидад и Тобаго","Тунис","Турция","Туркменистан","Тувалу","Украина","Уругвай","Узбекистан","Вануату","Ватикан","Венесуэла","Великобритания","Вьетнам","Италия","Кот-д’Ивуар","Маршалловы Острова","Соломоновы Острова","Замбия","Зимбабве"];

  var KIN_EN = ["Grandmother","Brother","Nephew (brother's son)","Niece (brother's daughter)","Sister-in-law (brother's wife)","Aunt","Daughter","Son","Grandfather","Cousin (male)","Cousin (female)","Mother","Father","Partner","Stepson","Stepdaughter","Great-granddaughter","Great-grandson","Sister","Niece (sister's daughter)","Nephew (sister's son)","Uncle (father's brother)","Aunt (father's brother's wife)","Father-in-law","Mother-in-law","Granddaughter","Spouse (husband, wife)","Uncle (mother's brother)","Son-in-law"];
  var KIN_ES = ["Abuela","Hermano","Sobrino (hijo del hermano)","Sobrina (hija del hermano)","Cuñada (esposa del hermano)","Tía","Hija","Hijo","Abuelo","Primo","Prima","Madre","Padre","Pareja","Hijastro","Hijastra","Bisnieta","Bisnieto","Hermana","Sobrina (hija de la hermana)","Sobrino (hijo de la hermana)","Tío (hermano del padre)","Tía (esposa del tío paterno)","Suegro","Suegra","Nieta","Cónyuge (esposo, esposa)","Tío (hermano de la madre)","Yerno"];
  var KIN_UK = ["Бабуся","Брат","Племінник (син брата)","Племінниця (донька брата)","Невістка (дружина брата)","Тітка","Донька","Син","Дідусь","Двоюрідний брат","Двоюрідна сестра","Мати","Батько","Партнер/Партнерка","Пасинок","Падчерка","Правнучка","Правнук","Сестра","Племінниця (донька сестри)","Племінник (син сестри)","Дядько (брат батька)","Тітка (дружина дядька по батькові)","Тесть/Свекор","Теща/Свекруха","Онучка","Чоловік/дружина","Дядько (брат матері)","Зять"];
  var KIN_RU = ["Бабушка","Брат","Племянник (сын брата)","Племянница (дочь брата)","Невестка (жена брата)","Тётя","Дочь","Сын","Дедушка","Двоюродный брат","Двоюродная сестра","Мать","Отец","Партнёр/Партнёрша","Пасынок","Падчерица","Правнучка","Правнук","Сестра","Племянница (дочь сестры)","Племянник (сын сестры)","Дядя (брат отца)","Тётя (жена дяди по отцу)","Тесть/Свёкор","Тёща/Свекровь","Внучка","Супруг(а) (муж, жена)","Дядя (брат матери)","Зять"];

  function L(select, dash, remove, famMember, woman, man, yes, no, lblSex, lblBirth, lblKinship, lblCit, lblApply, lblDep, lblEntry, lblExit, lblDays, lblBasis, lblCountry, lblCitMain, lblProvRes, lblProvApp, stayBasis, kinship, countries){
    return {select:select,dash:dash,remove:remove,famMember:famMember,woman:woman,man:man,yes:yes,no:no,
      lblSex:lblSex,lblBirth:lblBirth,lblKinship:lblKinship,lblCit:lblCit,lblApply:lblApply,lblDep:lblDep,
      lblEntry:lblEntry,lblExit:lblExit,lblDays:lblDays,lblBasis:lblBasis,lblCountry:lblCountry,
      lblCitMain:lblCitMain,lblProvRes:lblProvRes,lblProvApp:lblProvApp,
      stayBasis:stayBasis,kinship:kinship,countries:countries};
  }
  return {
    pl: L('— Proszę wybrać —','—','Usuń ✕','Członek rodziny','kobieta','mężczyzna','Tak','Nie',
      'Płeć','Data urodzenia','Stopień pokrewieństwa','Obywatelstwo','Ubiega się o pobyt czasowy?','Na utrzymaniu wnioskodawcy?','Data wjazdu','Data wyjazdu','Liczba dni','Podstawa pobytu','Państwo',
      'Obywatelstwo','Województwo miejsca pobytu','W jakim województwie złożono wniosek?',
      ["Wiza","Ruch bezwizowy","Karta pobytu","Inny dokument"], null, null),
    en: L('— Please select —','—','Remove ✕','Family member','female','male','Yes','No',
      'Sex','Date of birth','Degree of kinship','Citizenship','Applying for temporary residence?','Dependent on the applicant?','Date of entry','Date of exit','Number of days','Basis of stay','Country',
      'Citizenship','Voivodeship of residence','In which voivodeship was the application filed?',
      ["Visa","Visa-free travel","Residence card","Other document"], KIN_EN, COUNTRIES_EN),
    es: L('— Elige por favor —','—','Eliminar ✕','Miembro de la familia','mujer','hombre','Sí','No',
      'Sexo','Fecha de nacimiento','Grado de parentesco','Ciudadanía','¿Solicita residencia temporal?','¿A cargo del solicitante?','Fecha de entrada','Fecha de salida','Número de días','Base de la estancia','País',
      'Ciudadanía','Voivodato del lugar de residencia','¿En qué voivodato se presentó la solicitud?',
      ["Visado","Circulación sin visado","Tarjeta de residencia","Otro documento"], KIN_ES, COUNTRIES_ES),
    uk: L('— Оберіть, будь ласка —','—','Видалити ✕','Член родини','жінка','чоловік','Так','Ні',
      'Стать','Дата народження','Ступінь спорідненості','Громадянство','Подає на тимчасове проживання?','На утриманні заявника?','Дата в’їзду','Дата виїзду','Кількість днів','Підстава перебування','Держава',
      'Громадянство','Воєводство місця перебування','У якому воєводстві подано заяву?',
      ["Віза","Безвізовий режим","Карта перебування","Інший документ"], KIN_UK, COUNTRIES_UK),
    ru: L('— Выберите, пожалуйста —','—','Удалить ✕','Член семьи','женщина','мужчина','Да','Нет',
      'Пол','Дата рождения','Степень родства','Гражданство','Подаёт на временное пребывание?','На иждивении заявителя?','Дата въезда','Дата выезда','Количество дней','Основание пребывания','Страна',
      'Гражданство','Воеводство места пребывания','В каком воеводстве подано заявление?',
      ["Виза","Безвизовый режим","Карта пребывания","Другой документ"], KIN_RU, COUNTRIES_RU)
  };
})();

/* Rozszerzenie: teksty sterowane przez JS (pasek postępu, przyciski, podsumowanie, komunikaty) */
(function(){
  var WA='<a href="https://wa.me/48539999549">WhatsApp +48 539 999 549</a>';
  var MAIL='<a href="mailto:office@cosc.org.pl">office@cosc.org.pl</a>';
  var E = {
    pl:{ steps:["Zgoda","Dane","Pobyt","Rodzina","Historia","Pytania","Wyślij"],
      btnPrev:"← Wstecz", btnNext:"Dalej →", btnSubmit:"Wyślij ankietę", sending:"Wysyłanie…", retry:"Spróbuj wysłać ponownie",
      days:"dni", future:"data w przyszłości",
      summary:["Imię i nazwisko","Data urodzenia","Obywatelstwo","E-mail","Telefon własny","Telefon polski","Dni od ostatniego wjazdu","Rodzaj wniosku","Świadczenie","Pracodawca","NIP pracodawcy","Rodzaj umowy","Wynagrodzenie brutto","Praca od","Województwo pobytu","Rodzina w Polsce"],
      msgOk:"Dziękujemy! Ankieta została wysłana do kancelarii. Skontaktujemy się z Tobą, aby wspólnie dokończyć wniosek. Kopię PDF ankiety możesz pobrać przyciskiem poniżej. Pamiętaj o przesłaniu skanu paszportu na WhatsApp lub e-mail.",
      msgErr:"Nie udało się wysłać ankiety automatycznie. Skontaktuj się z nami bezpośrednio: "+WA+" lub "+MAIL+", a Twoje odpowiedzi prześlemy ręcznie." },
    en:{ steps:["Consent","Data","Stay","Family","History","Questions","Send"],
      btnPrev:"← Back", btnNext:"Next →", btnSubmit:"Send questionnaire", sending:"Sending…", retry:"Try sending again",
      days:"days", future:"date in the future",
      summary:["Full name","Date of birth","Citizenship","E-mail","Own phone","Polish phone","Days since last entry","Application type","Benefit","Employer","Employer NIP","Type of contract","Gross salary","Working since","Voivodeship of residence","Family in Poland"],
      msgOk:"Thank you! The questionnaire has been sent to the law office. We will contact you to complete the application together. You can download a PDF copy using the button below. Remember to send a scan of your passport via WhatsApp or e-mail.",
      msgErr:"The questionnaire could not be sent automatically. Please contact us directly: "+WA+" or "+MAIL+", and we will submit your answers manually." },
    es:{ steps:["Consentimiento","Datos","Estancia","Familia","Historial","Preguntas","Enviar"],
      btnPrev:"← Atrás", btnNext:"Siguiente →", btnSubmit:"Enviar cuestionario", sending:"Enviando…", retry:"Intenta enviar de nuevo",
      days:"días", future:"fecha en el futuro",
      summary:["Nombre y apellido","Fecha de nacimiento","Ciudadanía","Correo electrónico","Teléfono propio","Teléfono polaco","Días desde la última entrada","Tipo de solicitud","Prestación","Empleador","NIP del empleador","Tipo de contrato","Salario bruto","Trabaja desde","Voivodato de residencia","Familia en Polonia"],
      msgOk:"¡Gracias! El cuestionario ha sido enviado al despacho. Nos pondremos en contacto contigo para completar juntos la solicitud. Puedes descargar una copia en PDF con el botón de abajo. Recuerda enviar un escaneo de tu pasaporte por WhatsApp o correo.",
      msgErr:"No se pudo enviar el cuestionario automáticamente. Contáctanos directamente: "+WA+" o "+MAIL+", y enviaremos tus respuestas manualmente." },
    uk:{ steps:["Згода","Дані","Перебування","Родина","Історія","Питання","Надіслати"],
      btnPrev:"← Назад", btnNext:"Далі →", btnSubmit:"Надіслати анкету", sending:"Надсилання…", retry:"Спробувати надіслати ще раз",
      days:"днів", future:"дата в майбутньому",
      summary:["Ім’я та прізвище","Дата народження","Громадянство","E-mail","Власний телефон","Польський телефон","Днів від останнього в’їзду","Тип заяви","Виплата","Роботодавець","NIP роботодавця","Вид договору","Зарплата брутто","Працює з","Воєводство перебування","Родина в Польщі"],
      msgOk:"Дякуємо! Анкету надіслано до канцелярії. Ми зв’яжемося з Вами, щоб разом завершити заяву. Копію PDF можна завантажити кнопкою нижче. Не забудьте надіслати скан паспорта у WhatsApp або на e-mail.",
      msgErr:"Не вдалося надіслати анкету автоматично. Зв’яжіться з нами напряму: "+WA+" або "+MAIL+", і ми надішлемо Ваші відповіді вручну." },
    ru:{ steps:["Согласие","Данные","Пребывание","Семья","История","Вопросы","Отправить"],
      btnPrev:"← Назад", btnNext:"Далее →", btnSubmit:"Отправить анкету", sending:"Отправка…", retry:"Попробовать отправить снова",
      days:"дней", future:"дата в будущем",
      summary:["Имя и фамилия","Дата рождения","Гражданство","E-mail","Собственный телефон","Польский телефон","Дней с последнего въезда","Тип заявления","Выплата","Работодатель","NIP работодателя","Вид договора","Зарплата брутто","Работает с","Воеводство пребывания","Семья в Польше"],
      msgOk:"Спасибо! Анкета отправлена в канцелярию. Мы свяжемся с Вами, чтобы вместе завершить заявление. Копию PDF можно скачать кнопкой ниже. Не забудьте прислать скан паспорта в WhatsApp или на e-mail.",
      msgErr:"Не удалось отправить анкету автоматически. Свяжитесь с нами напрямую: "+WA+" или "+MAIL+", и мы отправим Ваши ответы вручную." }
  };
  var F=window.FORM_L10N; for(var k in E){ if(F[k]) for(var p in E[k]) F[k][p]=E[k][p]; }
})();
